In [598]:
import numpy as np

In [599]:
import os

In [600]:
z = [1,2,3,4,5]

In [601]:
w = 2*z
w

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [602]:
x = [6,5,4,3,2,1]

In [603]:
r = w + x
r

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 6, 5, 4, 3, 2, 1]

In [604]:
a = [1,3,5,7,9]

In [605]:
print(a[2:4])

[5, 7]


In [606]:
b = ([1,3,5,9],[2,4,6,8,10])

In [607]:
print(b[0])

[1, 3, 5, 9]


In [608]:
print(b[1][2:4])

[6, 8]


In [610]:
a = np.array([1,2,3,4,5,6])
b = np.array([6,5,4,3,2,1])

In [611]:
a

array([1, 2, 3, 4, 5, 6])

In [612]:
c = 2*a

In [613]:
print (c)

[ 2  4  6  8 10 12]


In [614]:
type(c)

numpy.ndarray

In [615]:
c.shape

(6,)

In [616]:
l = [[1, 2, 3], [3, 6, 9], [2, 4, 6]] # create a list

In [617]:
a = np.array(l) # convert a list to an array

In [618]:
print(a)

[[1 2 3]
 [3 6 9]
 [2 4 6]]


In [619]:
a.shape

(3, 3)

In [620]:
print(a.dtype)

int64


In [621]:
M = np.array([[1, 2], [3, 4]])

In [622]:
M.shape

(2, 2)

In [623]:
M.dtype

dtype('int64')

In [624]:
M = np.array([[1, 2], [3, 4]], dtype=complex)
M

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [625]:
print(a)


[[1 2 3]
 [3 6 9]
 [2 4 6]]


In [626]:
print(a[0])

[1 2 3]


In [627]:
print(a[1, 2]) # arrays can be given comma separated indices

9


In [628]:
print(a[1, 1:3])

[6 9]


In [629]:
print(a[:,1])

[2 6 4]


In [630]:
a[1, 2] = 7

In [631]:
print(a)


[[1 2 3]
 [3 6 7]
 [2 4 6]]


In [632]:
a[:, 0] = [0, 9, 8]

In [633]:
print(a)


[[0 2 3]
 [9 6 7]
 [8 4 6]]


In [634]:
x = np.arange(0, 10, 1)

In [635]:
np.linspace(0, 10, 25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [636]:
np.logspace(0, 10, 10, base=numpy.e)

array([1.00000000e+00, 3.03773178e+00, 9.22781435e+00, 2.80316249e+01,
       8.51525577e+01, 2.58670631e+02, 7.85771994e+02, 2.38696456e+03,
       7.25095809e+03, 2.20264658e+04])

In [637]:
# a diagonal matrix
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [638]:
b = np.zeros(5)
print(b)

[0. 0. 0. 0. 0.]


In [639]:
b.dtype

dtype('float64')

In [640]:
n = 1000


In [641]:
np.int = int

In [642]:
my_int_array = np.zeros(n, dtype=np.int)

In [643]:
my_int_array.dtype

dtype('int64')

In [644]:
c = np.ones((3,3))


In [645]:
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [646]:
d = np.arange(5) # just like range()

In [647]:
print(d)

[0 1 2 3 4]


In [648]:
d[1] = 9.7

In [649]:
print(d) # arrays keep their type even if elements changed

[0 9 2 3 4]


In [650]:
print(d*0.4) # operations create a new array, with new type

[0.  3.6 0.8 1.2 1.6]


In [651]:
d = [np.arange(5, dtype=np.float)]

In [652]:
print(d)


[array([0., 1., 2., 3., 4.])]


In [653]:
np.arange(3, 7, 0.5) # arbitrary start, stop and step

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [654]:
x, y = np.mgrid[0:5, 0:5] # similar to meshgrid in MATLAB
x

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [655]:
# random data
np.random.rand(5,5)

array([[0.30360267, 0.72923607, 0.5760826 , 0.45309826, 0.44826515],
       [0.96100122, 0.14608379, 0.10294547, 0.24633036, 0.68256532],
       [0.53645393, 0.63128501, 0.89987047, 0.53912747, 0.20756836],
       [0.94836748, 0.66248025, 0.47437101, 0.30901408, 0.34747205],
       [0.37191206, 0.62422666, 0.25995985, 0.50375784, 0.08545843]])

In [660]:
os.system('head DeBilt.txt')

1

In [661]:
np.savetxt('datasaved.txt', data)

NameError: name 'data' is not defined

In [658]:
os.system('head datasaved.txt')

1

In [ ]:
M = np.random.rand(3,3)
M

In [ ]:
np.save('saved-matrix.npy', M)
np.load('saved-matrix.npy’)

In [ ]:
a = numpy.arange(4.0)
b = a * 23.4
c = b/(a+1)
c += 10

In [ ]:
print (c)

In [348]:
arr = np.arange(100, 200)

In [349]:
select = [5, 25, 50, 75, -5]

In [ ]:
print(arr[select]) # can use integer lists as indices

In [354]:
arr = np.arange(10, 20).reshape((2,5))

In [ ]:
arr.sum()

In [ ]:
arr.mean()

In [ ]:
arr.std()

In [ ]:
arr.max()

In [ ]:
arr.min()

In [357]:
arr = np.array([4.5, 2.3, 6.7, 1.2, 1.8, 5.5])

In [ ]:
arr.sort() # acts on array itself
print(arr)

In [ ]:
x = np.array([4.5, 2.3, 6.7, 1.2, 1.8, 5.5])
np.sort(x)

In [ ]:
print(x)

In [ ]:
a = array([[1.0, 2.0], [4.0, 3.0]])
print a

In [ ]:
a.transpose()

In [ ]:
inv(a)

In [ ]:
u = eye(2) # unit 2x2 matrix; "eye" represents "I"
u

In [ ]:
j = array([[0.0, -1.0], [1.0, 0.0]])

In [ ]:
dot (j, j) # matrix product

In [ ]:
a = np.array([1,2,3], float)
b = np.array([5,2,6], float)
a + b

In [ ]:
a - b

In [ ]:
a * b

In [ ]:
b / a

In [ ]:
a % b

In [ ]:
b**a

In [ ]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([-1, 3], float)
a

In [ ]:
b

In [ ]:
a + b

In [380]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([-1, 3], float)

In [ ]:
a * a

In [ ]:
b * b

In [ ]:
a * b