In [1]:
z = [1,2,3,4,5]

In [2]:
w = 2*z
w

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [3]:
x = [6,5,4,3,2,1]

In [4]:
r = w + x
r

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 6, 5, 4, 3, 2, 1]

In [5]:
a = [1,3,5,7,9]

In [6]:
print(a[2:4])

[5, 7]


In [11]:
b = ([1,3,5,9],[2,4,6,8,10])

In [12]:
print(b[0])

[1, 3, 5, 9]


In [14]:
print(b[1][2:4])

[6, 8]


In [7]:
import numpy as np

In [8]:
a = np.array([1,2,3,4,5,6])
b = np.array([6,5,4,3,2,1])

In [9]:
a

array([1, 2, 3, 4, 5, 6])

In [17]:
c = 2*a

In [19]:
print (c)

[ 2  4  6  8 10 12]


In [21]:
type(c)

numpy.ndarray

In [22]:
c.shape

(6,)

In [23]:
l = [[1, 2, 3], [3, 6, 9], [2, 4, 6]] # create a list

In [24]:
a = np.array(l) # convert a list to an array

In [25]:
print(a)

[[1 2 3]
 [3 6 9]
 [2 4 6]]


In [26]:
a.shape

(3, 3)

In [27]:
print(a.dtype)

int64


In [39]:
M = np.array([[1, 2], [3, 4]])

In [40]:
M.shape

(2, 2)

In [41]:
M.dtype

dtype('int64')

In [43]:
M = np.array([[1, 2], [3, 4]], dtype=complex)
M

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [45]:
print(a)


[[1 2 3]
 [3 6 9]
 [2 4 6]]


In [46]:
print(a[0])

[1 2 3]


In [47]:
print(a[1, 2]) # arrays can be given comma separated indices

9


In [48]:
print(a[1, 1:3])

[6 9]


In [49]:
print(a[:,1])

[2 6 4]


In [50]:
a[1, 2] = 7

In [51]:
print(a)


[[1 2 3]
 [3 6 7]
 [2 4 6]]


In [52]:
a[:, 0] = [0, 9, 8]

In [53]:
print(a)


[[0 2 3]
 [9 6 7]
 [8 4 6]]


In [57]:
x = arange(0, 10, 1) # arguments: start, stop, step
x

NameError: name 'arange' is not defined

In [59]:
np.linspace(0, 10, 25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [60]:
np.logspace(0, 10, 10, base=numpy.e)

NameError: name 'numpy' is not defined

In [61]:
# a diagonal matrix
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [62]:
b = np.zeros(5)
print(b)

[0. 0. 0. 0. 0.]


In [63]:
b.dtype

dtype('float64')

In [65]:
n = 1000


In [1]:
my_int_array = np.zeros(n, dtype=np.int)

NameError: name 'np' is not defined

In [68]:
my_int_array.dtype

NameError: name 'my_int_array' is not defined