## NUMPY TAREA 1
Ilse AR

In [64]:
import numpy as np

In [65]:
import os

In [66]:
z = [1,2,3,4,5]

In [67]:
w = 2*z
w

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [68]:
x = [6,5,4,3,2,1]

In [69]:
r = w + x
r

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 6, 5, 4, 3, 2, 1]

In [70]:
a = [1,3,5,7,9]

In [71]:
print(a[2:4])

[5, 7]


In [72]:
b = ([1,3,5,9],[2,4,6,8,10])

In [73]:
print(b[0])

[1, 3, 5, 9]


In [74]:
print(b[1][2:4])

[6, 8]


In [75]:
a = np.array([1,2,3,4,5,6])
b = np.array([6,5,4,3,2,1])

In [76]:
a

array([1, 2, 3, 4, 5, 6])

In [77]:
c = 2*a

In [78]:
print (c)

[ 2  4  6  8 10 12]


In [79]:
type(c)

numpy.ndarray

In [80]:
c.shape

(6,)

In [81]:
l = [[1, 2, 3], [3, 6, 9], [2, 4, 6]] # create a list

In [82]:
a = np.array(l) # convert a list to an array

In [83]:
print(a)

[[1 2 3]
 [3 6 9]
 [2 4 6]]


In [84]:
a.shape

(3, 3)

In [85]:
print(a.dtype)

int64


In [86]:
M = np.array([[1, 2], [3, 4]])

In [87]:
M.shape

(2, 2)

In [88]:
M.dtype

dtype('int64')

In [89]:
M = np.array([[1, 2], [3, 4]], dtype=complex)
M

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [90]:
print(a)


[[1 2 3]
 [3 6 9]
 [2 4 6]]


In [91]:
print(a[0])

[1 2 3]


In [92]:
print(a[1, 2]) # arrays can be given comma separated indices

9


In [93]:
print(a[1, 1:3])

[6 9]


In [94]:
print(a[:,1])

[2 6 4]


In [95]:
a[1, 2] = 7

In [96]:
print(a)


[[1 2 3]
 [3 6 7]
 [2 4 6]]


In [97]:
a[:, 0] = [0, 9, 8]

In [98]:
print(a)


[[0 2 3]
 [9 6 7]
 [8 4 6]]


In [99]:
x = np.arange(0, 10, 1)

In [100]:
np.linspace(0, 10, 25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [101]:
np.logspace(0, 10, 10, base=np.e)

array([1.00000000e+00, 3.03773178e+00, 9.22781435e+00, 2.80316249e+01,
       8.51525577e+01, 2.58670631e+02, 7.85771994e+02, 2.38696456e+03,
       7.25095809e+03, 2.20264658e+04])

In [102]:
# a diagonal matrix
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [103]:
b = np.zeros(5)
print(b)

[0. 0. 0. 0. 0.]


In [104]:
b.dtype

dtype('float64')

In [105]:
n = 1000


In [106]:
np.int = int

In [107]:
my_int_array = np.zeros(n, dtype=np.int)

In [108]:
my_int_array.dtype

dtype('int64')

In [109]:
c = np.ones((3,3))


In [110]:
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [111]:
d = np.arange(5) # just like range()

In [112]:
print(d)

[0 1 2 3 4]


In [113]:
d[1] = 9.7

In [114]:
print(d) # arrays keep their type even if elements changed

[0 9 2 3 4]


In [115]:
print(d*0.4) # operations create a new array, with new type

[0.  3.6 0.8 1.2 1.6]


In [116]:
np.float = float

In [117]:
d = [np.arange(5, dtype=np.float)]

In [118]:
print(d)


[array([0., 1., 2., 3., 4.])]


In [119]:
np.arange(3, 7, 0.5) # arbitrary start, stop and step

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [120]:
x, y = np.mgrid[0:5, 0:5] # similar to meshgrid in MATLAB
x

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [121]:
# random data
np.random.rand(5,5)

array([[0.26458707, 0.1882516 , 0.05362872, 0.25622488, 0.4228775 ],
       [0.55890152, 0.99519168, 0.9277769 , 0.22793166, 0.43267752],
       [0.54970881, 0.05511687, 0.46962499, 0.4782233 , 0.2871031 ],
       [0.069331  , 0.57928638, 0.42015857, 0.63595729, 0.88268281],
       [0.25820555, 0.85975092, 0.22264137, 0.22490535, 0.47133442]])

In [122]:
os.system('head DeBilt.txt')

1

In [123]:
data = np.genfromtxt('DeBilt.txt'),

In [124]:
np.savetxt('datasaved.txt', data)

In [125]:
os.system('head datasaved.txt')

1

In [126]:
M = np.random.rand(3,3)
M

array([[0.69342747, 0.02450715, 0.9469213 ],
       [0.16051926, 0.094411  , 0.17033386],
       [0.68095739, 0.93217592, 0.06116481]])

In [127]:
np.save('saved-matrix.npy', M)

In [128]:
np.load('saved-matrix.npy')

array([[0.69342747, 0.02450715, 0.9469213 ],
       [0.16051926, 0.094411  , 0.17033386],
       [0.68095739, 0.93217592, 0.06116481]])

In [129]:
a = np.arange(4.0)


In [130]:
b = a * 23.4
c = b/(a+1)
c += 10
print (c)

[10.   21.7  25.6  27.55]


In [131]:
arr = np.arange(100, 200)

In [132]:
select = [5, 25, 50, 75, -5]

In [133]:
print(arr[select]) # can use integer lists as indices

[105 125 150 175 195]


In [134]:
arr = np.arange(10, 20).reshape((2,5))

In [135]:
arr.sum()

np.int64(145)

In [136]:
arr.mean()

np.float64(14.5)

In [137]:
arr.std()

np.float64(2.8722813232690143)

In [138]:
arr.max()

np.int64(19)

In [139]:
arr.min()

np.int64(10)

In [140]:
arr = np.array([4.5, 2.3, 6.7, 1.2, 1.8, 5.5])

In [141]:
arr.sort() # acts on array itself
print(arr)

[1.2 1.8 2.3 4.5 5.5 6.7]


In [142]:
x = np.array([4.5, 2.3, 6.7, 1.2, 1.8, 5.5])
np.sort(x)

array([1.2, 1.8, 2.3, 4.5, 5.5, 6.7])

In [143]:
print(x)

[4.5 2.3 6.7 1.2 1.8 5.5]


In [144]:
a = np.array([[1.0, 2.0], [4.0, 3.0]])

In [145]:
print (a)

[[1. 2.]
 [4. 3.]]


In [146]:
a.transpose()

array([[1., 4.],
       [2., 3.]])

In [147]:
A = np.array([[1, 2], [3, 4]])  # Example matrix
A_inv = np.linalg.inv(A)  # Compute the inverse
print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [148]:
u = np.eye(2)  # 2x2 identity matrix
print(u)

[[1. 0.]
 [0. 1.]]


In [149]:
j = np.array([[0.0, -1.0], [1.0, 0.0]])

In [150]:
np.dot (j, j) # matrix product

array([[-1.,  0.],
       [ 0., -1.]])

In [151]:
a = np.array([1,2,3], float)
b = np.array([5,2,6], float)
a + b

array([6., 4., 9.])

In [152]:
a - b

array([-4.,  0., -3.])

In [153]:
a * b

array([ 5.,  4., 18.])

In [154]:
b / a

array([5., 1., 2.])

In [155]:
a % b

array([1., 0., 3.])

In [156]:
b**a

array([  5.,   4., 216.])

In [157]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([-1, 3], float)
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [158]:
b

array([-1.,  3.])

In [159]:
a + b

array([[0., 5.],
       [2., 7.],
       [4., 9.]])

In [160]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([-1, 3], float)

In [161]:
a * a

array([[ 1.,  4.],
       [ 9., 16.],
       [25., 36.]])

In [162]:
b * b

array([1., 9.])

In [163]:
a * b

array([[-1.,  6.],
       [-3., 12.],
       [-5., 18.]])