In [216]:
import numpy as np

In [217]:
z = [1,2,3,4,5]

In [218]:
w = 2*z
w

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [219]:
x = [6,5,4,3,2,1]

In [220]:
r = w + x
r

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 6, 5, 4, 3, 2, 1]

In [221]:
a = [1,3,5,7,9]

In [222]:
print(a[2:4])

[5, 7]


In [223]:
b = ([1,3,5,9],[2,4,6,8,10])

In [224]:
print(b[0])

[1, 3, 5, 9]


In [225]:
print(b[1][2:4])

[6, 8]


In [226]:
import numpy as np

In [227]:
a = np.array([1,2,3,4,5,6])
b = np.array([6,5,4,3,2,1])

In [228]:
a

array([1, 2, 3, 4, 5, 6])

In [229]:
c = 2*a

In [230]:
print (c)

[ 2  4  6  8 10 12]


In [231]:
type(c)

numpy.ndarray

In [232]:
c.shape

(6,)

In [233]:
l = [[1, 2, 3], [3, 6, 9], [2, 4, 6]] # create a list

In [234]:
a = np.array(l) # convert a list to an array

In [235]:
print(a)

[[1 2 3]
 [3 6 9]
 [2 4 6]]


In [236]:
a.shape

(3, 3)

In [237]:
print(a.dtype)

int64


In [238]:
M = np.array([[1, 2], [3, 4]])

In [239]:
M.shape

(2, 2)

In [240]:
M.dtype

dtype('int64')

In [241]:
M = np.array([[1, 2], [3, 4]], dtype=complex)
M

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [242]:
print(a)


[[1 2 3]
 [3 6 9]
 [2 4 6]]


In [243]:
print(a[0])

[1 2 3]


In [244]:
print(a[1, 2]) # arrays can be given comma separated indices

9


In [245]:
print(a[1, 1:3])

[6 9]


In [246]:
print(a[:,1])

[2 6 4]


In [247]:
a[1, 2] = 7

In [248]:
print(a)


[[1 2 3]
 [3 6 7]
 [2 4 6]]


In [249]:
a[:, 0] = [0, 9, 8]

In [250]:
print(a)


[[0 2 3]
 [9 6 7]
 [8 4 6]]


In [251]:
x = np.arange(0, 10, 1)

In [252]:
np.linspace(0, 10, 25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [253]:
np.logspace(0, 10, 10, base=numpy.e)

array([1.00000000e+00, 3.03773178e+00, 9.22781435e+00, 2.80316249e+01,
       8.51525577e+01, 2.58670631e+02, 7.85771994e+02, 2.38696456e+03,
       7.25095809e+03, 2.20264658e+04])

In [254]:
# a diagonal matrix
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [255]:
b = np.zeros(5)
print(b)

[0. 0. 0. 0. 0.]


In [256]:
b.dtype

dtype('float64')

In [257]:
n = 1000


In [259]:
my_int_array = np.zeros(n, dtype=np.int)

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [260]:
my_int_array.dtype

NameError: name 'my_int_array' is not defined

In [261]:
c = np.ones((3,3))


In [ ]:
c

In [52]:
d = np.arange(5) # just like range()

In [ ]:
print(d)

In [54]:
d[1] = 9.7

In [ ]:
print(d) # arrays keep their type even if elements changed

In [ ]:
print(d*0.4) # operations create a new array, with new type

In [ ]:
d = (np.arange(5, dtype=np.float)

In [ ]:
print(d)
