In [662]:
import numpy as np

In [663]:
import os

In [664]:
z = [1,2,3,4,5]

In [665]:
w = 2*z
w

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [666]:
x = [6,5,4,3,2,1]

In [667]:
r = w + x
r

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 6, 5, 4, 3, 2, 1]

In [668]:
a = [1,3,5,7,9]

In [669]:
print(a[2:4])

[5, 7]


In [670]:
b = ([1,3,5,9],[2,4,6,8,10])

In [671]:
print(b[0])

[1, 3, 5, 9]


In [672]:
print(b[1][2:4])

[6, 8]


In [673]:
a = np.array([1,2,3,4,5,6])
b = np.array([6,5,4,3,2,1])

In [674]:
a

array([1, 2, 3, 4, 5, 6])

In [675]:
c = 2*a

In [676]:
print (c)

[ 2  4  6  8 10 12]


In [677]:
type(c)

numpy.ndarray

In [678]:
c.shape

(6,)

In [679]:
l = [[1, 2, 3], [3, 6, 9], [2, 4, 6]] # create a list

In [680]:
a = np.array(l) # convert a list to an array

In [681]:
print(a)

[[1 2 3]
 [3 6 9]
 [2 4 6]]


In [682]:
a.shape

(3, 3)

In [683]:
print(a.dtype)

int64


In [684]:
M = np.array([[1, 2], [3, 4]])

In [685]:
M.shape

(2, 2)

In [686]:
M.dtype

dtype('int64')

In [687]:
M = np.array([[1, 2], [3, 4]], dtype=complex)
M

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [688]:
print(a)


[[1 2 3]
 [3 6 9]
 [2 4 6]]


In [689]:
print(a[0])

[1 2 3]


In [690]:
print(a[1, 2]) # arrays can be given comma separated indices

9


In [691]:
print(a[1, 1:3])

[6 9]


In [692]:
print(a[:,1])

[2 6 4]


In [693]:
a[1, 2] = 7

In [694]:
print(a)


[[1 2 3]
 [3 6 7]
 [2 4 6]]


In [695]:
a[:, 0] = [0, 9, 8]

In [696]:
print(a)


[[0 2 3]
 [9 6 7]
 [8 4 6]]


In [697]:
x = np.arange(0, 10, 1)

In [698]:
np.linspace(0, 10, 25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [699]:
np.logspace(0, 10, 10, base=numpy.e)

array([1.00000000e+00, 3.03773178e+00, 9.22781435e+00, 2.80316249e+01,
       8.51525577e+01, 2.58670631e+02, 7.85771994e+02, 2.38696456e+03,
       7.25095809e+03, 2.20264658e+04])

In [700]:
# a diagonal matrix
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [701]:
b = np.zeros(5)
print(b)

[0. 0. 0. 0. 0.]


In [702]:
b.dtype

dtype('float64')

In [703]:
n = 1000


In [704]:
np.int = int

In [705]:
my_int_array = np.zeros(n, dtype=np.int)

In [706]:
my_int_array.dtype

dtype('int64')

In [707]:
c = np.ones((3,3))


In [708]:
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [709]:
d = np.arange(5) # just like range()

In [710]:
print(d)

[0 1 2 3 4]


In [711]:
d[1] = 9.7

In [712]:
print(d) # arrays keep their type even if elements changed

[0 9 2 3 4]


In [713]:
print(d*0.4) # operations create a new array, with new type

[0.  3.6 0.8 1.2 1.6]


In [714]:
d = [np.arange(5, dtype=np.float)]

In [715]:
print(d)


[array([0., 1., 2., 3., 4.])]


In [716]:
np.arange(3, 7, 0.5) # arbitrary start, stop and step

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [717]:
x, y = np.mgrid[0:5, 0:5] # similar to meshgrid in MATLAB
x

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [718]:
# random data
np.random.rand(5,5)

array([[0.76356489, 0.04726907, 0.47991604, 0.20465171, 0.60282321],
       [0.93710633, 0.06885196, 0.03200319, 0.79005529, 0.6337105 ],
       [0.68563764, 0.0625429 , 0.53072643, 0.3519022 , 0.69939037],
       [0.84295321, 0.61420907, 0.28964461, 0.67884035, 0.5232816 ],
       [0.6283852 , 0.83802012, 0.07849875, 0.33211975, 0.51495876]])

In [719]:
os.system('head DeBilt.txt')

1

In [720]:
np.savetxt('datasaved.txt', data)

NameError: name 'data' is not defined

In [ ]:
os.system('head datasaved.txt')

In [ ]:
M = np.random.rand(3,3)
M

In [ ]:
np.save('saved-matrix.npy', M)
np.load('saved-matrix.npy’)

In [ ]:
a = numpy.arange(4.0)
b = a * 23.4
c = b/(a+1)
c += 10

In [ ]:
print (c)

In [348]:
arr = np.arange(100, 200)

In [349]:
select = [5, 25, 50, 75, -5]

In [ ]:
print(arr[select]) # can use integer lists as indices

In [354]:
arr = np.arange(10, 20).reshape((2,5))

In [ ]:
arr.sum()

In [ ]:
arr.mean()

In [ ]:
arr.std()

In [ ]:
arr.max()

In [ ]:
arr.min()

In [357]:
arr = np.array([4.5, 2.3, 6.7, 1.2, 1.8, 5.5])

In [ ]:
arr.sort() # acts on array itself
print(arr)

In [ ]:
x = np.array([4.5, 2.3, 6.7, 1.2, 1.8, 5.5])
np.sort(x)

In [ ]:
print(x)

In [ ]:
a = array([[1.0, 2.0], [4.0, 3.0]])
print a

In [ ]:
a.transpose()

In [ ]:
inv(a)

In [ ]:
u = eye(2) # unit 2x2 matrix; "eye" represents "I"
u

In [ ]:
j = array([[0.0, -1.0], [1.0, 0.0]])

In [ ]:
dot (j, j) # matrix product

In [ ]:
a = np.array([1,2,3], float)
b = np.array([5,2,6], float)
a + b

In [ ]:
a - b

In [ ]:
a * b

In [ ]:
b / a

In [ ]:
a % b

In [ ]:
b**a

In [ ]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([-1, 3], float)
a

In [ ]:
b

In [ ]:
a + b

In [380]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([-1, 3], float)

In [ ]:
a * a

In [ ]:
b * b

In [ ]:
a * b