In [132]:
import numpy as np

In [133]:
import os

In [134]:
z = [1,2,3,4,5]

In [135]:
w = 2*z
w

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [136]:
x = [6,5,4,3,2,1]

In [137]:
r = w + x
r

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 6, 5, 4, 3, 2, 1]

In [138]:
a = [1,3,5,7,9]

In [139]:
print(a[2:4])

[5, 7]


In [140]:
b = ([1,3,5,9],[2,4,6,8,10])

In [141]:
print(b[0])

[1, 3, 5, 9]


In [142]:
print(b[1][2:4])

[6, 8]


In [143]:
a = np.array([1,2,3,4,5,6])
b = np.array([6,5,4,3,2,1])

In [144]:
a

array([1, 2, 3, 4, 5, 6])

In [145]:
c = 2*a

In [146]:
print (c)

[ 2  4  6  8 10 12]


In [147]:
type(c)

numpy.ndarray

In [148]:
c.shape

(6,)

In [149]:
l = [[1, 2, 3], [3, 6, 9], [2, 4, 6]] # create a list

In [150]:
a = np.array(l) # convert a list to an array

In [151]:
print(a)

[[1 2 3]
 [3 6 9]
 [2 4 6]]


In [152]:
a.shape

(3, 3)

In [153]:
print(a.dtype)

int64


In [154]:
M = np.array([[1, 2], [3, 4]])

In [155]:
M.shape

(2, 2)

In [156]:
M.dtype

dtype('int64')

In [157]:
M = np.array([[1, 2], [3, 4]], dtype=complex)
M

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [158]:
print(a)


[[1 2 3]
 [3 6 9]
 [2 4 6]]


In [159]:
print(a[0])

[1 2 3]


In [160]:
print(a[1, 2]) # arrays can be given comma separated indices

9


In [161]:
print(a[1, 1:3])

[6 9]


In [162]:
print(a[:,1])

[2 6 4]


In [163]:
a[1, 2] = 7

In [164]:
print(a)


[[1 2 3]
 [3 6 7]
 [2 4 6]]


In [165]:
a[:, 0] = [0, 9, 8]

In [166]:
print(a)


[[0 2 3]
 [9 6 7]
 [8 4 6]]


In [167]:
x = np.arange(0, 10, 1)

In [168]:
np.linspace(0, 10, 25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [169]:
np.logspace(0, 10, 10, base=numpy.e)

NameError: name 'numpy' is not defined

In [ ]:
# a diagonal matrix
np.diag([1,2,3])

In [ ]:
b = np.zeros(5)
print(b)

In [ ]:
b.dtype

In [89]:
n = 1000


In [90]:
np.int = int

In [91]:
my_int_array = np.zeros(n, dtype=np.int)

In [ ]:
my_int_array.dtype

In [93]:
c = np.ones((3,3))


In [ ]:
c

In [95]:
d = np.arange(5) # just like range()

In [ ]:
print(d)

In [97]:
d[1] = 9.7

In [ ]:
print(d) # arrays keep their type even if elements changed

In [ ]:
print(d*0.4) # operations create a new array, with new type

In [ ]:
d = [np.arange(5, dtype=np.float)]

In [ ]:
print(d)


In [ ]:
np.arange(3, 7, 0.5) # arbitrary start, stop and step

In [ ]:
x, y = np.mgrid[0:5, 0:5] # similar to meshgrid in MATLAB
x

In [ ]:
# random data
np.random.rand(5,5)

In [ ]:
os.system('head DeBilt.txt')

In [106]:
data = np.genfromtxt('DeBilt.txt'),

In [107]:
np.savetxt('datasaved.txt', data)

In [ ]:
os.system('head datasaved.txt')

In [ ]:
M = np.random.rand(3,3)
M

In [110]:
np.save('saved-matrix.npy', M)

In [ ]:
np.load('saved-matrix.npy’)

In [ ]:
a = numpy.arange(4.0)
b = a * 23.4
c = b/(a+1)
c += 10

In [ ]:
print (c)

In [114]:
arr = np.arange(100, 200)

In [115]:
select = [5, 25, 50, 75, -5]

In [ ]:
print(arr[select]) # can use integer lists as indices

In [117]:
arr = np.arange(10, 20).reshape((2,5))

In [ ]:
arr.sum()

In [ ]:
arr.mean()

In [ ]:
arr.std()

In [ ]:
arr.max()

In [ ]:
arr.min()

In [123]:
arr = np.array([4.5, 2.3, 6.7, 1.2, 1.8, 5.5])

In [ ]:
arr.sort() # acts on array itself
print(arr)

In [ ]:
x = np.array([4.5, 2.3, 6.7, 1.2, 1.8, 5.5])
np.sort(x)

In [ ]:
print(x)

In [ ]:
a = array([[1.0, 2.0], [4.0, 3.0]])

In [ ]:
print (a)

In [ ]:
a.transpose()

In [ ]:
inv(a)

In [ ]:
u = eye(2) # unit 2x2 matrix; "eye" represents "I"
u

In [ ]:
j = array([[0.0, -1.0], [1.0, 0.0]])

In [ ]:
dot (j, j) # matrix product

In [ ]:
a = np.array([1,2,3], float)
b = np.array([5,2,6], float)
a + b

In [ ]:
a - b

In [ ]:
a * b

In [ ]:
b / a

In [ ]:
a % b

In [ ]:
b**a

In [ ]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([-1, 3], float)
a

In [ ]:
b

In [ ]:
a + b

In [380]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([-1, 3], float)

In [ ]:
a * a

In [ ]:
b * b

In [ ]:
a * b