In [725]:
import numpy as np

In [726]:
import os

In [727]:
z = [1,2,3,4,5]

In [728]:
w = 2*z
w

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [729]:
x = [6,5,4,3,2,1]

In [730]:
r = w + x
r

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 6, 5, 4, 3, 2, 1]

In [731]:
a = [1,3,5,7,9]

In [732]:
print(a[2:4])

[5, 7]


In [733]:
b = ([1,3,5,9],[2,4,6,8,10])

In [734]:
print(b[0])

[1, 3, 5, 9]


In [735]:
print(b[1][2:4])

[6, 8]


In [736]:
a = np.array([1,2,3,4,5,6])
b = np.array([6,5,4,3,2,1])

In [737]:
a

array([1, 2, 3, 4, 5, 6])

In [738]:
c = 2*a

In [739]:
print (c)

[ 2  4  6  8 10 12]


In [740]:
type(c)

numpy.ndarray

In [741]:
c.shape

(6,)

In [742]:
l = [[1, 2, 3], [3, 6, 9], [2, 4, 6]] # create a list

In [743]:
a = np.array(l) # convert a list to an array

In [744]:
print(a)

[[1 2 3]
 [3 6 9]
 [2 4 6]]


In [745]:
a.shape

(3, 3)

In [746]:
print(a.dtype)

int64


In [747]:
M = np.array([[1, 2], [3, 4]])

In [748]:
M.shape

(2, 2)

In [749]:
M.dtype

dtype('int64')

In [750]:
M = np.array([[1, 2], [3, 4]], dtype=complex)
M

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [751]:
print(a)


[[1 2 3]
 [3 6 9]
 [2 4 6]]


In [752]:
print(a[0])

[1 2 3]


In [753]:
print(a[1, 2]) # arrays can be given comma separated indices

9


In [754]:
print(a[1, 1:3])

[6 9]


In [755]:
print(a[:,1])

[2 6 4]


In [756]:
a[1, 2] = 7

In [757]:
print(a)


[[1 2 3]
 [3 6 7]
 [2 4 6]]


In [758]:
a[:, 0] = [0, 9, 8]

In [759]:
print(a)


[[0 2 3]
 [9 6 7]
 [8 4 6]]


In [760]:
x = np.arange(0, 10, 1)

In [761]:
np.linspace(0, 10, 25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [762]:
np.logspace(0, 10, 10, base=numpy.e)

array([1.00000000e+00, 3.03773178e+00, 9.22781435e+00, 2.80316249e+01,
       8.51525577e+01, 2.58670631e+02, 7.85771994e+02, 2.38696456e+03,
       7.25095809e+03, 2.20264658e+04])

In [763]:
# a diagonal matrix
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [764]:
b = np.zeros(5)
print(b)

[0. 0. 0. 0. 0.]


In [765]:
b.dtype

dtype('float64')

In [766]:
n = 1000


In [767]:
np.int = int

In [768]:
my_int_array = np.zeros(n, dtype=np.int)

In [769]:
my_int_array.dtype

dtype('int64')

In [770]:
c = np.ones((3,3))


In [771]:
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [772]:
d = np.arange(5) # just like range()

In [773]:
print(d)

[0 1 2 3 4]


In [774]:
d[1] = 9.7

In [775]:
print(d) # arrays keep their type even if elements changed

[0 9 2 3 4]


In [776]:
print(d*0.4) # operations create a new array, with new type

[0.  3.6 0.8 1.2 1.6]


In [777]:
d = [np.arange(5, dtype=np.float)]

In [778]:
print(d)


[array([0., 1., 2., 3., 4.])]


In [779]:
np.arange(3, 7, 0.5) # arbitrary start, stop and step

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [780]:
x, y = np.mgrid[0:5, 0:5] # similar to meshgrid in MATLAB
x

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [781]:
# random data
np.random.rand(5,5)

array([[0.00599011, 0.08395219, 0.35081905, 0.2147808 , 0.7367196 ],
       [0.84356807, 0.62459217, 0.09676709, 0.86812792, 0.040449  ],
       [0.92487558, 0.33327079, 0.37124593, 0.90497097, 0.50184518],
       [0.56063836, 0.0144538 , 0.17162723, 0.2607197 , 0.59874151],
       [0.86667479, 0.65266888, 0.08939667, 0.6772291 , 0.00915455]])

In [782]:
os.system('head DeBilt.txt')

1

In [783]:
data = np.genfromtxt('DeBilt.txt'),

In [784]:
np.savetxt('datasaved.txt', data)

In [785]:
os.system('head datasaved.txt')

1

In [786]:
M = np.random.rand(3,3)
M

array([[0.864617  , 0.35283977, 0.12518729],
       [0.77564829, 0.21452952, 0.746081  ],
       [0.9576291 , 0.14514106, 0.27200474]])

In [788]:
np.save('saved-matrix.npy', M)

In [789]:
np.load('saved-matrix.npy’)

SyntaxError: EOL while scanning string literal (1981810579.py, line 1)

In [ ]:
a = numpy.arange(4.0)
b = a * 23.4
c = b/(a+1)
c += 10

In [ ]:
print (c)

In [348]:
arr = np.arange(100, 200)

In [349]:
select = [5, 25, 50, 75, -5]

In [ ]:
print(arr[select]) # can use integer lists as indices

In [354]:
arr = np.arange(10, 20).reshape((2,5))

In [ ]:
arr.sum()

In [ ]:
arr.mean()

In [ ]:
arr.std()

In [ ]:
arr.max()

In [ ]:
arr.min()

In [357]:
arr = np.array([4.5, 2.3, 6.7, 1.2, 1.8, 5.5])

In [ ]:
arr.sort() # acts on array itself
print(arr)

In [ ]:
x = np.array([4.5, 2.3, 6.7, 1.2, 1.8, 5.5])
np.sort(x)

In [ ]:
print(x)

In [ ]:
a = array([[1.0, 2.0], [4.0, 3.0]])
print a

In [ ]:
a.transpose()

In [ ]:
inv(a)

In [ ]:
u = eye(2) # unit 2x2 matrix; "eye" represents "I"
u

In [ ]:
j = array([[0.0, -1.0], [1.0, 0.0]])

In [ ]:
dot (j, j) # matrix product

In [ ]:
a = np.array([1,2,3], float)
b = np.array([5,2,6], float)
a + b

In [ ]:
a - b

In [ ]:
a * b

In [ ]:
b / a

In [ ]:
a % b

In [ ]:
b**a

In [ ]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([-1, 3], float)
a

In [ ]:
b

In [ ]:
a + b

In [380]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([-1, 3], float)

In [ ]:
a * a

In [ ]:
b * b

In [ ]:
a * b