In [271]:
import numpy as np

In [272]:
z = [1,2,3,4,5]

In [273]:
w = 2*z
w

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [274]:
x = [6,5,4,3,2,1]

In [275]:
r = w + x
r

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 6, 5, 4, 3, 2, 1]

In [276]:
a = [1,3,5,7,9]

In [277]:
print(a[2:4])

[5, 7]


In [278]:
b = ([1,3,5,9],[2,4,6,8,10])

In [279]:
print(b[0])

[1, 3, 5, 9]


In [280]:
print(b[1][2:4])

[6, 8]


In [281]:
import numpy as np

In [282]:
a = np.array([1,2,3,4,5,6])
b = np.array([6,5,4,3,2,1])

In [283]:
a

array([1, 2, 3, 4, 5, 6])

In [284]:
c = 2*a

In [285]:
print (c)

[ 2  4  6  8 10 12]


In [286]:
type(c)

numpy.ndarray

In [287]:
c.shape

(6,)

In [288]:
l = [[1, 2, 3], [3, 6, 9], [2, 4, 6]] # create a list

In [289]:
a = np.array(l) # convert a list to an array

In [290]:
print(a)

[[1 2 3]
 [3 6 9]
 [2 4 6]]


In [291]:
a.shape

(3, 3)

In [292]:
print(a.dtype)

int64


In [293]:
M = np.array([[1, 2], [3, 4]])

In [294]:
M.shape

(2, 2)

In [295]:
M.dtype

dtype('int64')

In [296]:
M = np.array([[1, 2], [3, 4]], dtype=complex)
M

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [297]:
print(a)


[[1 2 3]
 [3 6 9]
 [2 4 6]]


In [298]:
print(a[0])

[1 2 3]


In [299]:
print(a[1, 2]) # arrays can be given comma separated indices

9


In [300]:
print(a[1, 1:3])

[6 9]


In [301]:
print(a[:,1])

[2 6 4]


In [302]:
a[1, 2] = 7

In [303]:
print(a)


[[1 2 3]
 [3 6 7]
 [2 4 6]]


In [304]:
a[:, 0] = [0, 9, 8]

In [305]:
print(a)


[[0 2 3]
 [9 6 7]
 [8 4 6]]


In [306]:
x = np.arange(0, 10, 1)

In [307]:
np.linspace(0, 10, 25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [308]:
np.logspace(0, 10, 10, base=numpy.e)

array([1.00000000e+00, 3.03773178e+00, 9.22781435e+00, 2.80316249e+01,
       8.51525577e+01, 2.58670631e+02, 7.85771994e+02, 2.38696456e+03,
       7.25095809e+03, 2.20264658e+04])

In [309]:
# a diagonal matrix
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [310]:
b = np.zeros(5)
print(b)

[0. 0. 0. 0. 0.]


In [311]:
b.dtype

dtype('float64')

In [312]:
n = 1000


In [313]:
my_int_array = np.zeros(n, dtype=np.int)

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [314]:
my_int_array.dtype

NameError: name 'my_int_array' is not defined

In [315]:
c = np.ones((3,3))


In [316]:
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [317]:
d = np.arange(5) # just like range()

In [318]:
print(d)

[0 1 2 3 4]


In [319]:
d[1] = 9.7

In [320]:
print(d) # arrays keep their type even if elements changed

[0 9 2 3 4]


In [321]:
print(d*0.4) # operations create a new array, with new type

[0.  3.6 0.8 1.2 1.6]


In [322]:
d = (np.arange(5, dtype=np.float)

SyntaxError: unexpected EOF while parsing (3231391151.py, line 1)

In [323]:
print(d)


[0 9 2 3 4]
