In [384]:
import numpy as np

In [385]:
z = [1,2,3,4,5]

In [386]:
w = 2*z
w

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [387]:
x = [6,5,4,3,2,1]

In [388]:
r = w + x
r

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 6, 5, 4, 3, 2, 1]

In [389]:
a = [1,3,5,7,9]

In [390]:
print(a[2:4])

[5, 7]


In [391]:
b = ([1,3,5,9],[2,4,6,8,10])

In [392]:
print(b[0])

[1, 3, 5, 9]


In [393]:
print(b[1][2:4])

[6, 8]


In [394]:
import numpy as np

In [395]:
a = np.array([1,2,3,4,5,6])
b = np.array([6,5,4,3,2,1])

In [396]:
a

array([1, 2, 3, 4, 5, 6])

In [397]:
c = 2*a

In [398]:
print (c)

[ 2  4  6  8 10 12]


In [399]:
type(c)

numpy.ndarray

In [400]:
c.shape

(6,)

In [401]:
l = [[1, 2, 3], [3, 6, 9], [2, 4, 6]] # create a list

In [402]:
a = np.array(l) # convert a list to an array

In [403]:
print(a)

[[1 2 3]
 [3 6 9]
 [2 4 6]]


In [404]:
a.shape

(3, 3)

In [405]:
print(a.dtype)

int64


In [406]:
M = np.array([[1, 2], [3, 4]])

In [407]:
M.shape

(2, 2)

In [408]:
M.dtype

dtype('int64')

In [409]:
M = np.array([[1, 2], [3, 4]], dtype=complex)
M

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [410]:
print(a)


[[1 2 3]
 [3 6 9]
 [2 4 6]]


In [411]:
print(a[0])

[1 2 3]


In [412]:
print(a[1, 2]) # arrays can be given comma separated indices

9


In [413]:
print(a[1, 1:3])

[6 9]


In [414]:
print(a[:,1])

[2 6 4]


In [415]:
a[1, 2] = 7

In [416]:
print(a)


[[1 2 3]
 [3 6 7]
 [2 4 6]]


In [417]:
a[:, 0] = [0, 9, 8]

In [418]:
print(a)


[[0 2 3]
 [9 6 7]
 [8 4 6]]


In [419]:
x = np.arange(0, 10, 1)

In [420]:
np.linspace(0, 10, 25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [421]:
np.logspace(0, 10, 10, base=numpy.e)

array([1.00000000e+00, 3.03773178e+00, 9.22781435e+00, 2.80316249e+01,
       8.51525577e+01, 2.58670631e+02, 7.85771994e+02, 2.38696456e+03,
       7.25095809e+03, 2.20264658e+04])

In [422]:
# a diagonal matrix
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [423]:
b = np.zeros(5)
print(b)

[0. 0. 0. 0. 0.]


In [424]:
b.dtype

dtype('float64')

In [425]:
n = 1000


In [426]:
my_int_array = np.zeros(n, dtype=np.int)

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [ ]:
my_int_array.dtype

In [315]:
c = np.ones((3,3))


In [ ]:
c

In [317]:
d = np.arange(5) # just like range()

In [ ]:
print(d)

In [319]:
d[1] = 9.7

In [ ]:
print(d) # arrays keep their type even if elements changed

In [ ]:
print(d*0.4) # operations create a new array, with new type

In [ ]:
d = (np.arange(5, dtype=np.float)

In [ ]:
print(d)


In [ ]:
np.arange(3, 7, 0.5) # arbitrary start, stop and step

In [ ]:
x, y = np.mgrid[0:5, 0:5] # similar to meshgrid in MATLAB
x

In [ ]:
# random data
np.random.rand(5,5)

In [ ]:
os.system('head DeBilt.txt')

In [ ]:
np.savetxt('datasaved.txt', data)

In [ ]:
os.system('head datasaved.txt')

In [ ]:
M = np.random.rand(3,3)
M

In [ ]:
np.save('saved-matrix.npy', M)
np.load('saved-matrix.npy’)

In [ ]:
a = numpy.arange(4.0)
b = a * 23.4
c = b/(a+1)
c += 10

In [ ]:
print (c)

In [348]:
arr = np.arange(100, 200)

In [349]:
select = [5, 25, 50, 75, -5]

In [ ]:
print(arr[select]) # can use integer lists as indices

In [354]:
arr = np.arange(10, 20).reshape((2,5))

In [ ]:
arr.sum()

In [ ]:
arr.mean()

In [ ]:
arr.std()

In [ ]:
arr.max()

In [ ]:
arr.min()

In [357]:
arr = np.array([4.5, 2.3, 6.7, 1.2, 1.8, 5.5])

In [ ]:
arr.sort() # acts on array itself
print(arr)

In [ ]:
x = np.array([4.5, 2.3, 6.7, 1.2, 1.8, 5.5])
np.sort(x)

In [ ]:
print(x)

In [ ]:
a = array([[1.0, 2.0], [4.0, 3.0]])
print a

In [ ]:
a.transpose()

In [ ]:
inv(a)

In [ ]:
u = eye(2) # unit 2x2 matrix; "eye" represents "I"
u

In [ ]:
j = array([[0.0, -1.0], [1.0, 0.0]])

In [ ]:
dot (j, j) # matrix product

In [ ]:
a = np.array([1,2,3], float)
b = np.array([5,2,6], float)
a + b

In [ ]:
a - b

In [ ]:
a * b

In [ ]:
b / a

In [ ]:
a % b

In [ ]:
b**a

In [ ]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([-1, 3], float)
a

In [ ]:
b

In [ ]:
a + b

In [380]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([-1, 3], float)

In [ ]:
a * a

In [ ]:
b * b

In [ ]:
a * b