In [715]:
pip install --upgrade numpy

Note: you may need to restart the kernel to use updated packages.


In [716]:
import numpy as np

In [717]:
import os

In [718]:
z = [1,2,3,4,5]

In [719]:
w = 2*z
w

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [720]:
x = [6,5,4,3,2,1]

In [721]:
r = w + x
r

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 6, 5, 4, 3, 2, 1]

In [722]:
a = [1,3,5,7,9]

In [723]:
print(a[2:4])

[5, 7]


In [724]:
b = ([1,3,5,9],[2,4,6,8,10])

In [725]:
print(b[0])

[1, 3, 5, 9]


In [726]:
print(b[1][2:4])

[6, 8]


In [727]:
a = np.array([1,2,3,4,5,6])
b = np.array([6,5,4,3,2,1])

In [728]:
a

array([1, 2, 3, 4, 5, 6])

In [729]:
c = 2*a

In [730]:
print (c)

[ 2  4  6  8 10 12]


In [731]:
type(c)

numpy.ndarray

In [732]:
c.shape

(6,)

In [733]:
l = [[1, 2, 3], [3, 6, 9], [2, 4, 6]] # create a list

In [734]:
a = np.array(l) # convert a list to an array

In [735]:
print(a)

[[1 2 3]
 [3 6 9]
 [2 4 6]]


In [736]:
a.shape

(3, 3)

In [737]:
print(a.dtype)

int64


In [738]:
M = np.array([[1, 2], [3, 4]])

In [739]:
M.shape

(2, 2)

In [740]:
M.dtype

dtype('int64')

In [741]:
M = np.array([[1, 2], [3, 4]], dtype=complex)
M

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [742]:
print(a)


[[1 2 3]
 [3 6 9]
 [2 4 6]]


In [743]:
print(a[0])

[1 2 3]


In [744]:
print(a[1, 2]) # arrays can be given comma separated indices

9


In [745]:
print(a[1, 1:3])

[6 9]


In [746]:
print(a[:,1])

[2 6 4]


In [747]:
a[1, 2] = 7

In [748]:
print(a)


[[1 2 3]
 [3 6 7]
 [2 4 6]]


In [749]:
a[:, 0] = [0, 9, 8]

In [750]:
print(a)


[[0 2 3]
 [9 6 7]
 [8 4 6]]


In [751]:
x = np.arange(0, 10, 1)

In [752]:
np.linspace(0, 10, 25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [753]:
np.logspace(0, 10, 10, base=np.e)

array([1.00000000e+00, 3.03773178e+00, 9.22781435e+00, 2.80316249e+01,
       8.51525577e+01, 2.58670631e+02, 7.85771994e+02, 2.38696456e+03,
       7.25095809e+03, 2.20264658e+04])

In [754]:
# a diagonal matrix
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [755]:
b = np.zeros(5)
print(b)

[0. 0. 0. 0. 0.]


In [756]:
b.dtype

dtype('float64')

In [757]:
n = 1000


In [758]:
np.int = int

In [759]:
my_int_array = np.zeros(n, dtype=np.int)

In [760]:
my_int_array.dtype

dtype('int64')

In [761]:
c = np.ones((3,3))


In [762]:
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [763]:
d = np.arange(5) # just like range()

In [764]:
print(d)

[0 1 2 3 4]


In [765]:
d[1] = 9.7

In [766]:
print(d) # arrays keep their type even if elements changed

[0 9 2 3 4]


In [767]:
print(d*0.4) # operations create a new array, with new type

[0.  3.6 0.8 1.2 1.6]


In [768]:
np.float = float

In [769]:
d = [np.arange(5, dtype=np.float)]

In [770]:
print(d)


[array([0., 1., 2., 3., 4.])]


In [771]:
np.arange(3, 7, 0.5) # arbitrary start, stop and step

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [772]:
x, y = np.mgrid[0:5, 0:5] # similar to meshgrid in MATLAB
x

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [773]:
# random data
np.random.rand(5,5)

array([[0.97957884, 0.5281393 , 0.96604774, 0.8279042 , 0.05236129],
       [0.49970785, 0.38120607, 0.42140555, 0.48078069, 0.66497368],
       [0.92049737, 0.51420718, 0.22131662, 0.06447737, 0.01615607],
       [0.29684099, 0.95941015, 0.18628139, 0.91834739, 0.74830474],
       [0.92685294, 0.90305487, 0.94159503, 0.26790078, 0.78688649]])

In [774]:
os.system('head DeBilt.txt')

1

In [775]:
data = np.genfromtxt('DeBilt.txt'),

In [776]:
np.savetxt('datasaved.txt', data)

In [777]:
os.system('head datasaved.txt')

1

In [778]:
M = np.random.rand(3,3)
M

array([[0.44216986, 0.17180215, 0.88112439],
       [0.15052653, 0.82865812, 0.23617793],
       [0.75954796, 0.12276484, 0.63922335]])

In [779]:
np.save('saved-matrix.npy', M)

In [780]:
np.load('saved-matrix.npy')

array([[0.44216986, 0.17180215, 0.88112439],
       [0.15052653, 0.82865812, 0.23617793],
       [0.75954796, 0.12276484, 0.63922335]])

In [781]:
a = np.arange(4.0)


In [782]:
b = a * 23.4
c = b/(a+1)
c += 10
print (c)

[10.   21.7  25.6  27.55]


In [783]:
arr = np.arange(100, 200)

In [784]:
select = [5, 25, 50, 75, -5]

In [785]:
print(arr[select]) # can use integer lists as indices

[105 125 150 175 195]


In [786]:
arr = np.arange(10, 20).reshape((2,5))

In [787]:
arr.sum()

np.int64(145)

In [788]:
arr.mean()

np.float64(14.5)

In [789]:
arr.std()

np.float64(2.8722813232690143)

In [790]:
arr.max()

np.int64(19)

In [791]:
arr.min()

np.int64(10)

In [792]:
arr = np.array([4.5, 2.3, 6.7, 1.2, 1.8, 5.5])

In [793]:
arr.sort() # acts on array itself
print(arr)

[1.2 1.8 2.3 4.5 5.5 6.7]


In [794]:
x = np.array([4.5, 2.3, 6.7, 1.2, 1.8, 5.5])
np.sort(x)

array([1.2, 1.8, 2.3, 4.5, 5.5, 6.7])

In [795]:
print(x)

[4.5 2.3 6.7 1.2 1.8 5.5]


In [796]:
a = np.array([[1.0, 2.0], [4.0, 3.0]])

In [797]:
print (a)

[[1. 2.]
 [4. 3.]]


In [798]:
a.transpose()

array([[1., 4.],
       [2., 3.]])

In [799]:
A = np.array([[1, 2], [3, 4]])  # Example matrix
A_inv = np.linalg.inv(A)  # Compute the inverse
print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [800]:
u = np.eye(2)  # 2x2 identity matrix
print(u)

[[1. 0.]
 [0. 1.]]


In [801]:
j = np.array([[0.0, -1.0], [1.0, 0.0]])

In [802]:
np.dot (j, j) # matrix product

array([[-1.,  0.],
       [ 0., -1.]])

In [803]:
a = np.array([1,2,3], float)
b = np.array([5,2,6], float)
a + b

array([6., 4., 9.])

In [804]:
a - b

array([-4.,  0., -3.])

In [805]:
a * b

array([ 5.,  4., 18.])

In [806]:
b / a

array([5., 1., 2.])

In [807]:
a % b

array([1., 0., 3.])

In [808]:
b**a

array([  5.,   4., 216.])

In [809]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([-1, 3], float)
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [810]:
b

array([-1.,  3.])

In [811]:
a + b

array([[0., 5.],
       [2., 7.],
       [4., 9.]])

In [812]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([-1, 3], float)

In [813]:
a * a

array([[ 1.,  4.],
       [ 9., 16.],
       [25., 36.]])

In [814]:
b * b

array([1., 9.])

In [815]:
a * b

array([[-1.,  6.],
       [-3., 12.],
       [-5., 18.]])